### ISSUE TITLE
Missing Reference

### ISSUE THREAD

**Issue by NVentimiglia** [dotBunny/Hydrogen#3]
Error   1   The type or namespace name `Hydrogen' could not be found. Are you missing a using directive or an assembly reference?   Assets/Hydrogen Examples/Hydrogen Examples/Examples/Components/Input/Source/InputExample.cs 130 33  Solution 'UnityVS.Hydrogen' ‎(loading...)

I have a few of these. I downloaded the project from the asset store. Al 'h' files do not work.

**Comment by reapazor** [comment]
You also need the actual framework installed, it looks like you just
installed the examples package.

That hopefully should fix that ;)

On Monday, June 16, 2014, Nicholas Ventimiglia notifications@github.com
wrote:

> Error 1 The type or namespace name `Hydrogen' could not be found. Are you
> missing a using directive or an assembly reference? Assets/Hydrogen
> Examples/Hydrogen Examples/Examples/Components/Input/Source/InputExample.cs
> 130 33 Solution 'UnityVS.Hydrogen' ‎(loading...)
> 
> I have a few of these. I downloaded the project from the asset store. Al
> 'h' files do not work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dotBunny/Hydrogen/issues/3.

## 

---

Matthew Davey
dotBunny

705.201.1352 x111

**Comment by reapazor** [comment]
Closing for now :)
