### ISSUE TITLE
TestFlight is no longer offering the SDK - Submission gets rejected

### ISSUE THREAD

**Issue by diegoleao** [dotBunny/Hydrogen#6]
Testflight no longer offers its SDK to new users. When I submit my app using Hydrogen, I get a rejection notice because it includes the SDK.

Important: Only people who have never used TestFlight's SDK are being rejected. If you used it once in the past, they are accepting your submissions, if not they will block it.

Please test this issue using a new user in TestFlight, or else you will not see the issue.

**Comment by reapazor** [comment]
I think I'm going to remove test flight altogether, Apple really hasn't
commented on its future.

On Tuesday, September 30, 2014, diegoleao notifications@github.com wrote:

> Testflight no longer offers its SDK to new users. When I submit my app
> using Hydrogen, I get a rejection notice because it includes the SDK.
> 
> Important: Only people who have never used TestFlight's SDK are being
> rejected. If you used it once in the past, they are accepting your
> submissions, if not they will block it.
> 
> Please test this issue using a new user in TestFlight, or else you will
> not see the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dotBunny/Hydrogen/issues/6.

## 

---

Matthew Davey
dotBunny

888.632.1993 x700

**Comment by diegoleao** [comment]
Yeah, I think that is wise :\ By this point it is clear they are winding down this feature.

I was under the impression I had to include the SDK to submit to TestFlight, when in fact it is not required at all to share alpha/beta software through their system. 

You can just upoad your binary as-is and it works no problem :\ I wasted a lot of time :)

I guess for people who still have this feature enabled on their accounts, you could offer older versions of Hydrogen, or something like that... But for new people, they will just waste time like I did using Hydrogen to integrate the SDK...
